config/routes.rb
Rails.application.routes.draw do
  resources :feelings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'feelings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  validates :content, length: { maximum: 1000, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :set_feeling, only: [:show, :edit, :update, :destroy]

  # GET /feelings
  # GET /feelings.json
  def index
    @feeling = Feeling.new
    @feelings = Feeling.order(created_at: :desc)
                       .page(params[:page])
                       .per(50)
  end

  # GET /feelings/1
  # GET /feelings/1.json
  def show
  end

  # GET /feelings/new
  def new
    @feeling = Feeling.new
  end

  # GET /feelings/1/edit
  def edit
  end

  # POST /feelings
  # POST /feelings.json
  def create
    @feeling = Feeling.new(feeling_params)
    @feeling.user_agent = request.user_agent
    @feeling.ip = request.ip
    @feeling.save
  end

  # PATCH/PUT /feelings/1
  # PATCH/PUT /feelings/1.json
  def update
    respond_to do |format|
      if @feeling.update(feeling_params)
        format.html { redirect_to @feeling, notice: 'Feeling was successfully updated.' }
        format.json { render :show, status: :ok, location: @feeling }
      else
        format.html { render :edit }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feelings/1
  # DELETE /feelings/1.json
  def destroy
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to feelings_url, notice: 'Feeling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feeling
      @feeling = Feeling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feeling_params
      params.require(:feeling).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_feeling.html.erb
<% cache feeling do %>
  <div class="card">
    <%= simple_format feeling.content.strip %>
    <p class="hint feeling-date">
      <%= feeling.created_at %>
    </p>
  </div>
<% end %>

app/views/feelings/_form.html.erb
<%= form_for feeling, remote: true do |f| %>
  <div contenteditable="true" data-feeling-input autofocus=true>
    <%= feeling.content %>
  </div>
  <div class="hidden">
    <%= f.text_area :content, hidden: true %>
  </div>
  <% if feeling.errors.any? %>
    <div class="errors">
      <%= feeling.errors.full_messages.join("; ") %>
    </div>
  <% end %>
  <%= f.button "Let it all out", class: "feeling-submit" %>
  <p class="hint submit-hint">Or press ctrl+enter to submit</p>
<% end %>

app/views/feelings/create.js.erb
var formContainer     = document.querySelector("[data-feeling-form]");
var feelingsContainer = document.querySelector("[data-feelings]");


<% if @feeling.invalid? %>
  formContainer.innerHTML = "<%= escape_javascript render('form', feeling: @feeling) %>";
<% else %>
  formContainer.innerHTML = "<%= escape_javascript render('form', feeling: Feeling.new) %>";
  feelingsContainer.insertAdjacentHTML("afterbegin", "<%= escape_javascript render('feeling', feeling: @feeling) %>");
<% end %>

focusFeelingInput();
bindFeelingEvents();

app/views/feelings/edit.html.erb
<h1>Editing Feeling</h1>

<%= render 'form', feeling: @feeling %>

<%= link_to 'Show', @feeling %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/index.html.erb
<div class="heading">
  <h1 class="title">What are you feeling?</h1>
  <p class="hint" data-heading-hint>
    Need to vent? Tell the world how you're feeling.
  </p>
  <div data-feeling-form>
    <%= render 'form', feeling: @feeling %>
  </div>
</div>

<div data-feelings class="feelings">
  <%= render partial: 'feeling', collection: @feelings, cached: true %>
  <%= paginate @feelings %>
</div>

app/views/feelings/new.html.erb
<h1>New Feeling</h1>

<%= render 'form', feeling: @feeling %>

<%= link_to 'Back', feelings_path %>

app/views/feelings/show.html.erb
<%= @feeling.content %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>What are you feeling?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="Need to vent? Tell the world how you're feeling.">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>